### PR TITLE
135 create login and sign-up page

### PR DESCRIPTION
**Pull request by Dinesh-Khanal**
Hi lugenx,
I have created the login and sign-up page as per the Figma designs provided by you. Please review these and let me know if something have to be changed.

### CODE REVIEW

**Comment by tsimian** [comment]
@lugenx I can help with this review

**Comment by lugenx** [comment]
> @lugenx I can help with this review

thank you for your help, please go ahead.

**Comment by rcamach7** [comment]
Great work! It looks very good. Here's my feedback:

On mobile, we should probably skip displaying this component: 
Screenshot 2023-03-06 at 5 38 32 PM

and skip right into showing the login form
Screenshot 2023-03-06 at 5 39 56 PM

Meaning "Main" components display should be set to none on the mobile breakpoint, and just default to showing the Login component @lugenx @tsimian  thoughts on this?

**Comment by rcamach7** [comment]
Also, we can create a custom react hook that will give us the available height on the screen, taking into consideration the app bar. We can then use the value from that to size the rest of the content on the site, so the app bar + page content fill the entire page without overflowing. 

Thoughts on this being a separate ticket @lugenx ?

**Comment by lugenx** [comment]
> Great work! It looks very good. Here's my feedback:
> 
> On mobile, we should probably skip displaying this component: Screenshot 2023-03-06 at 5 38 32 PM
> 
> and skip right into showing the login form Screenshot 2023-03-06 at 5 39 56 PM
> 
> Meaning "Main" components display should be set to none on the mobile breakpoint, and just default to showing the Login component @lugenx @tsimian thoughts on this?

I agree eliminating an extra step will lead to a better user experience.

**Comment by lugenx** [comment]
> Also, we can create a custom react hook that will give us the available height on the screen, taking into consideration the app bar. We can then use the value from that to size the rest of the content on the site, so the app bar + page content fill the entire page without overflowing.
> 
> Thoughts on this being a separate ticket @lugenx ?

sounds good. yeah, I think that can be a separate ticket.

**Comment by tsimian** [comment]
@rcamach, that sounds good to me

**Comment by rcamach7** [comment]
Ok I have created the ticket, so once this is done, we can pull in that functionality in another PR

**Comment by Dinesh-Khanal** [comment]
@rcamach7 , @tsimian , @lugenx I go with you and make change accordingly. I have done my best still there my be something wrong unknowingly, if so please inform me.

**Review by rcamach7 — APPROVED** [review]
Looks good to me! Great work @Dinesh-Khanal

**Review by lugenx — APPROVED** [review]
thank you guys

**Pull request merged**
