### PR TITLE
Renamed how-to-contribute.md file

### LINKED ISSUE #92: Rename "how-to-contribute.md" file to "CONTRIBUTING.md" and move it to the root folder.
This will make GitHub recognize the file and show the users wherever it's needed most.

### PR DESCRIPTION
**Pull request by Rishav1707**
### This PR closes the following issue:-
closes #92 

### Changes made:-
- Renamed the `how-to-contribute.md` file to `contributing.md` file.
- Move `contributing.md` file to the root folder.

### CODE REVIEW

**Review by AbhiBajpaishek — APPROVED** [review]

**Comment by lugenx** [comment]
thank you for this, can i ask one more thing before the merge.

in the README file, last bullet of `Contribute` section, there is a link (beginner-friendly guide) directed to how-to-contribute.md file, can we update that as well so it points to the newly renamed file and new location?

**Comment by Rishav1707** [comment]
> thank you for this, can i ask one more thing before the merge.
> 
> in the README file, last bullet of `Contribute` section, there is a link (beginner-friendly guide) directed to how-to-contribute.md file, can we update that as well so it points to the newly renamed file and new location?

Ok

**Comment by Rishav1707** [comment]
> thank you for this, can i ask one more thing before the merge.
> 
> in the README file, last bullet of `Contribute` section, there is a link (beginner-friendly guide) directed to how-to-contribute.md file, can we update that as well so it points to the newly renamed file and new location?

Done @lugenx

**Comment by lugenx** [comment]
in the "issue", i mentioned renaming and moving the file, but it looks like i missed a lot of things that would happen when we do these actions. i just realized the screenshots on the contributing instructions are not working because they lost the link with the pictures in the docs/assets folder. let me know if you want to fix these issues too, or i can create another "issue" for that.

**Comment by Rishav1707** [comment]
> in the "issue", i mentioned renaming and moving the file, but it looks like i missed a lot of things that would happen when we do these actions. i just realized the screenshots on the contributing instructions are not working because they lost the link with the pictures in the docs/assets folder. let me know if you want to fix these issues too, or i can create another "issue" for that.

Let me try then I'll report you

**Comment by Rishav1707** [comment]
> in the "issue", i mentioned renaming and moving the file, but it looks like i missed a lot of things that would happen when we do these actions. i just realized the screenshots on the contributing instructions are not working because they lost the link with the pictures in the docs/assets folder. let me know if you want to fix these issues too, or i can create another "issue" for that.

Done @lugenx

**Review by lugenx — APPROVED** [review]
thank you 👍

**Comment by Rishav1707** [comment]
> thank you 👍

Your welcome

**Pull request merged**
