### PR TITLE
Here are the new changes

### PR DESCRIPTION
**Pull request by mahir118**

### CODE REVIEW

**Comment by lugenx** [comment]
hi @mahir118 , thank you for this, when you get updates requests on a pull request, please push your changes to the same branch, that way you don't have to create new pull request for each update.
also, I recommend you to give more specific names to your pull requests that explains the issue you address.

**Comment by mahir118** [comment]
Hi @lugenx, thanks a lot for letting me know. I am trying to push my changes to 'added_ResponsiveAppBar' branch but I am getting 'everything up-to-date' on my terminal. Is there something I can do? Thank you so much for your help.

**Comment by rcamach7** [comment]
@mahir118 try switching branches to `added_ResponsiveAppBar`, copying over these changes, and doing a `git add .` and a git commit. Afterwards try pushing and let us know if that works.

(right now you are working with two different branches)

**Comment by mahir118** [comment]
Thanks for your help @rcamach7. I tried doing as you said but I am still getting 'everything up to date' in my terminal. I switched my branch (git checkout added_ResponsiveAppBar) and then I made the changes, added them, and pushed them. Can you please let me know what am I doing wrong?

**Comment by rcamach7** [comment]
> Thanks for your help @rcamach7. I tried doing as you said but I am still getting 'everything up to date' in my terminal. I switched my branch (git checkout added_ResponsiveAppBar) and then I made the changes, added them, and pushed them. Can you please let me know what am I doing wrong?

Looks like your forked repo hasn't received any of the changes you made locally. 

Run `git push origin added_responsiveAppBar` and let me know what you get

**Comment by mahir118** [comment]
> > Thanks for your help @rcamach7. I tried doing as you said but I am still getting 'everything up to date' in my terminal. I switched my branch (git checkout added_ResponsiveAppBar) and then I made the changes, added them, and pushed them. Can you please let me know what am I doing wrong?
> 
> Looks like your forked repo hasn't received any of the changes you made locally.
> 
> Run `git push origin added_responsiveAppBar` and let me know what you get

I am getting the same message i.e. Everything up-to-date

**Pull request closed without merging**
