### PR TITLE
fix issue #183

### PR DESCRIPTION
**Pull request by victorchrollo14**
Replaced "lorem ipsum" on login page with "Spreading awareness through, Sustainable actions."

### CODE REVIEW

**Comment by lugenx** [comment]
thanks for this @victorchrollo14 , a question: any reason we increased the line height?

**Comment by lugenx** [comment]
@victorchrollo14  it seems that you have increased the line height to avoid letter overlap. to address this, could you please change the "s" in the word "sustainable" to lowercase? Once that is done, you can set the line height back to 3.25.

**Review by tsimian — COMMENTED** [review]
I agree with you about the letter height @lugenx. Other than that it looks good to me. Great work @victorchrollo14!

**Comment by victorchrollo14** [comment]
Alright @lugenx @tsimian, Should I delete this pull request and create a new one from another branch.

**Pull request closed without merging**
