### PR TITLE
Add habits in user model

### PR DESCRIPTION
**Pull request by vishwaszadte**
#### CHANGED
- Changed the `User` model to add `habits` field, which is an array of `ObjectIds` that represent the `habits` selected by the specific user.

### CODE REVIEW

**Comment by vishwaszadte** [comment]
@lugenx PR ready for review

**Comment by vishwaszadte** [comment]
@lugenx I think we need to use `nodemon` for the live reload on the backend. Doing `npm start` every time there is a change is not productive. What say?

**Comment by lugenx** [comment]
> @lugenx I think we need to use `nodemon` for the live reload on the backend. Doing `npm start` every time there is a change is not productive. What say? You can create a new issue for this or I can even include it in this PR itself

@vishwaszadte yes, that is a helpful tool, but I think if anyone likes to use it, they can install their own computer globally. also, if you are using Node 20, you can use `node --watch`, i know it is still at an experimental stage, but its been working very well for me. I have never needed nodemon after upgrading my Node.JS.

**Comment by lugenx** [comment]
> @lugenx PR ready for review

This is perfect! Thank you! 👍

**Comment by vishwaszadte** [comment]
> > @lugenx I think we need to use `nodemon` for the live reload on the backend. Doing `npm start` every time there is a change is not productive. What say? You can create a new issue for this or I can even include it in this PR itself
> 
> @vishwaszadte yes, that is a helpful tool, but I think if anyone likes to use it, they can install their own computer globally. also, if you are using Node 20, you can use `node --watch`, i know it is still at an experimental stage, but its been working very well for me. I have never needed nodemon after upgrading my Node.JS.

@lugenx  oh.. I didn't know node had something like this internally, will give it a try

**Review by lugenx — APPROVED** [review]

**Pull request merged**
