### PR TITLE
fix/217 Remove Unnecessary Folder Nesting in Components

### PR DESCRIPTION
**Pull request by anmol111pal**
Hey @lugenx & @tsimian  , I have fixed the issue #217 .
Kindly review the PR & merge it.

### CODE REVIEW

**Comment by anmol111pal** [comment]
Hey @tsimian , kindly review the PR and merge it accordingly.
If it requires any further rectification, do let me know.

**Review by tsimian — COMMENTED** [review]
This looks good @lugenx, and great work @anmol111pal! Do you want to do the same for pages?

**Comment by anmol111pal** [comment]
> This looks good @lugenx, and great work @anmol111pal! Do you want to do the same for pages?

Thanks, I would like to work on the pages/ directory as well.
Please assign it to me .

**Comment by anmol111pal** [comment]
Hey, you haven't yet merged the PR.

**Comment by lugenx** [comment]
> > This looks good @lugenx, and great work @anmol111pal! Do you want to do the same for pages?
> 
> Thanks, I would like to work on the pages/ directory as well. Please assign it to me .

Hey, @anmol111pal , thanks for your interest. if you would like to work do the same thing for the pages directory, please feel free to create a similar issue, you can use #217 as an example. I would be happy to assign that issue to you.

**Review by lugenx — APPROVED** [review]
great, good work, thank you @anmol111pal

**Pull request merged**
