### PR TITLE
Docs/Habits - Markdown Update

### LINKED ISSUE #16: Rename nav-menu-items.md file to habits.md and improve document like in comments
In the changed document, we will have 4 categories for now: 
Recycle, Commute, Eat, and Energy.

Each Category will need habits like the below with the following format:

### Category: "Recycle." 
- **Habit 1**
  - **Description:** "Reduce the amount of waste by using reusable bags!"
  - **Question:** "Which of these did you use today?"
  - **Answer Options:** "Reusable bag," "Single-use plastic bag," "Both," "None."
 - **Habit 2**
   - ...

### **Category:** "Commute"
- **Habit 1** 
  - **Description:** "Consider carpooling with coworkers or friends. This can reduce the number of cars on the road and save on fuel."
  - **Question:** "How did you commute to work today?"
  - **Answer Options:** "Drive," "Carpool," "Bike," "Public Transport."
 - **Habit 2**
   - ...

### PR DESCRIPTION
**Pull request by rafaover**
- Followed basic instructions about the format.
- Relocated some information.

### CODE REVIEW

**Review by lugenx — CHANGES_REQUESTED** [review]
hi @rafaover, thanks for your effort. Unfortunately this changes doesn't match what is requested in the issue #16. Please read the issue body, and let me know if something is not clear. We can also have a quick call, so I can explain how these habits will need to be if that way would help better.

**Comment by rafaover** [comment]
It's not clear. You gave the structure, but I need to know if the content needs to be created or if you just wanted the structure for posterior edit. If you want the content to be created, is it from a specific source or is it free writing? Ty.

**Comment by lugenx** [comment]
Hey @rafaover, thanks for getting back! totally understand the confusion. let me clarify:

I'd like the document to have both the structure *and* content. The issue I created was meant to provide a guideline for the content too. for instance, under the "Recycle" category, the example habit's description was: "Reduce the amount of waste by using reusable bags!" 

so, for each habit:
- **Description**: It's free writing, but try to make it relevant and actionable.
- **Question**: Frame a question related to the habit, like I had in the example.
- **Answer Options**: These are potential answers for the previous question.

you don't need to pull from a specific source, but do make sure the habits and questions make sense in the context of the category. if you're unsure about a particular category or habit, just let me know! 

again, thanks for taking this on, and feel free to reach out if you have any other questions.

**Comment by lugenx** [comment]
hi @rafaover  hope you're doing well. Just checking in to see if there are any updates on this PR. Let me know if there's anything you need from my end!

**Comment by rafaover** [comment]
@lugenx No updates for now. I'm planning to sit and touch this next week. No Worries.

**Comment by lugenx** [comment]
@rafaover any update?

**Pull request closed without merging**
