### PR TITLE
" social " section in readme file updated.

### LINKED ISSUE #7: Update "socials" section in readme file

### PR DESCRIPTION
**Pull request by Rishav1707**
### This PR closes the following issue:
closes #7 

### Changes made:
- Added all the social icons of the contributors with their social link.

### CODE REVIEW

**Review by lugenx — CHANGES_REQUESTED** [review]
can we remove this section completely? since we will have a section to list the names, and also github is already listing the contributor names automatically.

**Comment by Rishav1707** [comment]
> can we remove this section completely? since we will have a section to list the names, and also github is already listing the contributor names automatically.

ok I'll remove it

**Comment by Rishav1707** [comment]
> can we remove this section completely? since we will have a section to list the names, and also github is already listing the contributor names automatically.

Done @lugenx

**Review by lugenx — APPROVED** [review]
thank you 👍

**Pull request merged**
