### PR TITLE
navbar design

### PR DESCRIPTION
**Pull request by WinterSunset95**
* Added a new file client/src/components/NavBar/Navbar.css
* Edited the NavBar.js file
*   ##Screenshot
image

### CODE REVIEW

**Comment by AbhiBajpaishek** [comment]
> also please delete any regular css files/stylings that already were replaced with mui styled components.

I think this comment is remaining and blocking this PR. @WinterSunset95 Did you get time to check this?

**Comment by rcamach7** [comment]
err

there appear to be issues with compiling @WinterSunset95

**Comment by WinterSunset95** [comment]
> err
> 
> there appear to be issues with compiling @WinterSunset95

I'm using react fontawesome for some icons
`npm install` in the client folder and you'll be fine

**Comment by lugenx** [comment]
> > also please delete any regular css files/stylings that already were replaced with mui styled components.
> 
> I think this comment is remaining and blocking this PR. @WinterSunset95 Did you get time to check this?

looks like we will have to address my comment later. i will merge this for now, since a lot of things will change, by using it as a reference. this is great work by the way, and will help us to move forward. thank you @WinterSunset95

**Review by lugenx — APPROVED** [review]

**Pull request merged**
