### PR TITLE
Prettier setting in config file in the repo now apply to all contributors code automatically

### PR DESCRIPTION
**Pull request by AyanDas348**
#94 Prettier setting in config file in the repo now apply to all contributors code automatically
-Added script in ./git/hooks/pre-commit:
  Run Prettier on all staged files
  npx prettier --write --config .prettierrc.json --ignore-path .gitignore --ignore-unknown .
-Made the script an executable file using:
  For windows: icacls .git/hooks/pre-commit /grant:r "%USERNAME%":F
  For Unix systems(Linux, macOS): git update-index --chmod=+x .git/hooks/pre-commit

### CODE REVIEW

**Comment by lugenx** [comment]
@AyanDas348 , thank you again, can you help me to understand where the script is exactly?

**Comment by AyanDas348** [comment]
@lugenx under ./git/hooks/pre-commit. The folder is hidden by default so you might need to turn on hidden folders in editors like VS Code to access it. It basically runs a script that says that before committing it will make changes to the files and folders in the folder: 
- --write: This flag tells Prettier to format the files in-place, meaning it will modify the files directly with the formatted code.
- --config .prettierrc.json: This flag specifies the configuration file for Prettier. In this case, it's .prettierrc.json
- --ignore-path .gitignore: This flag specifies the path to the .gitignore file. Prettier will ignore any files or directories listed in the .gitignore file.
- --ignore-unknown: This flag tells Prettier to ignore any unknown file types instead of throwing an error.
- .: The dot (.), Prettier will format all the files in the current directory and its subdirectories.

**Comment by lugenx** [comment]
thank you for the explanation, @AyanDas348. you're right that the `.git` folder exists on our local machines and doesn't get pushed to GitHub. doesn't this means that the `pre-commit` hook you've created currently only runs on your machine?

**Comment by AyanDas348** [comment]
@lugenx Whenever any contributor/users clone this repository they will also get the hooks from ./git/hooks cloned into their directory. When they commit it will apply the prettier changes as mentioned in .prettierrc.json file. I have made the pre-commit an executable so it runs when contributors make a commit.

**Comment by AyanDas348** [comment]
Hey @lugenx did you have the chance to take a look at this PR?

**Comment by lugenx** [comment]
hi @AyanDas348 ,

I cloned your branch and this is the .git/hooks folder looks like:
image

And this is the inside of precommit-sample file:
image

can you help me find out your script?

Thank you

**Comment by AyanDas348** [comment]
Hey @lugenx I have noticed my script has not been cloned. There is some issue with making the pre-commit hook executable and cloned. I'll look into this and start working out a new solution. Thanks for your patience.

**Comment by AyanDas348** [comment]
I will close the pull request and open a new one when I have resolved it. I'll make sure to reclone the repo on a different system to test if the pre-commit hook is working or not.

**Comment by lugenx** [comment]
sounds good, @AyanDas348 , thank you so much for looking into this, if you have any questions or just want to discuss while figuring this out, you can reach out to me or @tsimian in our discord chat. you can join the discord server through the link in the readme file if you didn't already.

**Comment by AyanDas348** [comment]
Thanks @lugenx I'll join the discord and let you know if I have a working solution.

**Pull request closed without merging**
