### PR TITLE
Added HabitCard

### PR DESCRIPTION
**Pull request by markhallak**
This PR closes issue #131

### CODE REVIEW

**Review by lugenx — CHANGES_REQUESTED** [review]
hi @markhallak , thank you for contributing. 
looks like you are adding the `.idea`, and `inspectionProfiles` folders. Can you please exclude it from the pull request?

**Comment by markhallak** [comment]
Deleted the files. Sorry about that.

**Review by rcamach7 — CHANGES_REQUESTED** [review]
@markhallak  It looks like you don't have prettier installed and set to format on save. To do this:

- Install the Prettier extension for VSCode.
- Open the VSCode settings, and search for prettier
- In the "Editor: Format On Save" setting, make sure it is turned on.
- Open the files you have worked on hit save.

After doing so go ahead and commit, and push

**Comment by markhallak** [comment]
I have installed Prettier, enabled "Format on save", and saved the document. No changes were made.

**Comment by rcamach7** [comment]
> I have installed Prettier, enabled "Format on save", and saved the document. No changes were made.

Try searching for "Prettier: Require Config" and turn it off, if on. Restart VSCode. Then try saving again, and see if it auto formats.

**Comment by markhallak** [comment]
It was off. I tried turning it on and off again. Still the same. What do you want me to do?

**Comment by rcamach7** [comment]
No worries, we'll format later, thank you! @markhallak

**Review by rcamach7 — APPROVED** [review]

**Review by lugenx — APPROVED** [review]

**Pull request merged**
