### PR TITLE
Prettier setting in config file in the repo now apply to all contributors code

### PR DESCRIPTION
**Pull request by AyanDas348**
- Added dev dependencies for prettier in the root directory
- Added script in ./git/hooks/pre-commit:
  Run Prettier on all staged files
  npx prettier --write --ignore-path .gitignore --ignore-unknown .
- Made the script an executable file using:
  For windows: icacls .git/hooks/pre-commit /grant:r "%USERNAME%":F
  For Unix systems(Linux, macOS): git update-index --chmod=+x .git/hooks/pre-commit
- Updated the README.md to make sure users/developers download the dev dependencies
- Added /node_modules in the .gitignore in the root directory

### CODE REVIEW

**Comment by lugenx** [comment]
Hi @AyanDas348, thank you for your contribution. I noticed that this PR introduces another `package.json` file in the root directory. Given the structure of this project, we have separate `package.json` files for the server and client side. Having a third one in the root directory might not align with the current structure. 

Could you please consider if there's another way we could address this issue that would be more in line with the existing project structure? I'm open to discussing this further if you have any thoughts or ideas.

**Comment by AyanDas348** [comment]
Hi @lugenx , we actually do not need the package.json file since we have the prettierrc.json file.

**Comment by lugenx** [comment]
@AyanDas348 that's great, whatever you prefer is fine.

**Comment by AyanDas348** [comment]
I have created a new PR with the updates.

**Pull request closed without merging**
